### ISSUE TITLE
No image and no movement recognition

### ISSUE THREAD

**Issue by Minipipo1** [hawksley/eleVR-Web-Player#13]
I have a problem with your player.
I have Windows 8.1, a firefox nightly build, a non-e10s window, the addon "WebVR Oculus Rift Enabler" enabled, the Oculus DK2 plugged and working very well with the demo application.
The problem is that when I try to user your demo, it doesn't work at all. I have the sound but no images at all, and I have an error in the developer console : "TypeError: state.orientation is null" on line 284.

I really don't understand... It's not a problem of video encoding since when my add-on is not enabled, I can watch the video without the oculus.It doesn't look that the problem is from my computer since I have another with the same configuration (8.1, firefox... etc.) and it's the same exact problem. I've also tried to restart my navigator twive and to unplug/replug my Oculus Rift DK2.

Do I have to install something I didn't, or is it a bug ?

**Comment by edwardrmiller** [comment]
This is the precise problem I am having with my work at http://hongkongunrest.com/vr-player.html

The video plays perfectly in Chrome and the video works on it's own in Nightly, but when viewed in the viewer, there is no video, though there is sound. Having emailed Andrea about the issue, she mentioned there may be a bug in Nightly. It would be interesting to get to the bottom of this.

Many thanks eleVR team for all your hard work.

**Comment by Minipipo1** [comment]
Yes many thanks, really I'm going to use this software really much since I now can use it ! I simply updated my Oculus Runtime... (sorry)

**Comment by hawksley** [comment]
Hi,
So, after talking to the firefox team, I've tracked down an *actual* issue in the eleVR code that at least partially caused this problem. I just pushed the fix to my main branch.

In the line where you check
```javascript
        if (typeof state.orientation !== 'undefined' &&
                  state.orientation.x !== 0 &&
                  state.orientation.y !== 0 &&
                  state.orientation.z !== 0 &&
                  state.orientation.w !== 0)
```

You need to modify to
```javascript
        if (state !== null && state.orientation !== null && typeof state.orientation !== 'undefined' &&
                  state.orientation.x !== 0 &&
                  state.orientation.y !== 0 &&
                  state.orientation.z !== 0 &&
                  state.orientation.w !== 0) {
```

Apparently updating the oculus runtime also helps =P
