### ISSUE TITLE
Add a regular view for desktop.

### ISSUE THREAD

**Issue by commit-master** [hawksley/eleVR-Web-Player#31]
Hey, nice work there @hawksley ! You really should had a default view before splitting the screen. Like having one video on the player (on desktop & tablet), instead of splitting it. And then add a button to split it. Would be really awesome !

GJ anyway

**Comment by mobiwu** [comment]
有中国的程序员在研究这个项目的吗？加我qq1332775639，一起来研究。
这个项目有视频锯齿的问题，你们怎么解决的呢？

**Comment by hahnzhu** [comment]
+1, it's necessary.

**Comment by JD557** [comment]
I think this project is no longer maintained.

I believe that you can find that feature in this fork: https://github.com/chenzlabs/eleVR-Web-Player

**Comment by hawksley** [comment]
Sorry, I have been on vacation. I have been intending to add this feature. In fact, it looks like that fork has added a lot of features that I have been too busy with other projects to get around to. @machenmusik are you ok with that?

**Comment by machenmusik** [comment]
I'm not actively working on that fork, slammed with other things lately,
may take a while to get anything useful done...
Is the ask to package up this feature as pull requests back to the original
project?

**Comment by hawksley** [comment]
Yes. You have made a bunch of great changes (not just this particular feature). It would be great to merge them into the original project. If it's ok with you and you aren't able to get around to making pull requests for features in the next while, I might also try to merge some of your changes into this project myself when I find the time.

Also, seeing how much I've been paying attention to this project, I totally understand being slammed with other things. :)

**Comment by machenmusik** [comment]
I will take a look when I get a chance - some changes are probably clean thus easy, others are probably quick-hack-poor-code that might not be worth it

**Comment by hawksley** [comment]
yup, I totally understand. That's how it tends to work.

**Comment by rpelleti22** [comment]
Is there a function or key combination that allows to switch from the default view to the split screen view in this version (below) of the player? I could not find any specific info in the readme file.
Thanks

> I think this project is no longer maintained.
> 
> I believe that you can find that feature in this fork: https://github.com/chenzlabs/eleVR-Web-Player

**Comment by hawksley** [comment]
just skimming the code, it looks like it just shows default view iff no headset is detected with no key or button to switch manually.

**Comment by danieltigse** [comment]
I create a switch button using a global variable called split and copying the changes that are in this commit 6e3d551e84e2fc8ce3629ea4a680c0acb86de0bf inside a condition like this:

```
if(webGL.split)
        webGL.gl.uniform1f(shader.uniforms['eye'], eye);
      else
        webGL.gl.uniform1f(shader.uniforms['eye'], eye & 1);
```

**Comment by rpelleti22** [comment]
Thanks Daniel,
Really helpful. Because I'm not familiar with anything related to videos, I would not have been able to do it completely on my own. 
Just a question: what is the function/purpose of that line: webGL.gl.uniform1f(shader.uniforms['eye'], eye);

Thanks!
