### ISSUE TITLE
Autoplay show black screen and only start sound

### ISSUE THREAD

**Issue by inquietto** [hawksley/eleVR-Web-Player#34]
Hello! Very good your work...
I've been testing and when the **autoplay** is in active mode, only the sound start and video no appears.
You know how I can solve it?
Thanks a lot!

**Comment by hawksley** [comment]
Can you give a full flow that causes this problem? And also a flow where you can see the video?

**Comment by inquietto** [comment]
Of course...
Here an example with problem
[](http://www.global-nomad.co/plays/vr/index.php)

**Comment by inquietto** [comment]
Basically the code I use is this

```
<Video src = "River.mp4" type = "video / mp4" class = "hidden" preload = "no" id = "video" loop = "true" crossOrigin = "anonymous" autoplay controls webkit-playsinline>
     </ Video>
```

**Comment by inquietto** [comment]
If can help to you ... when I click on the play button twice, the video appears correctly

**Comment by hawksley** [comment]
You are starting the video using autoplay of the video tag, but the part of the player that shows the video and does the video transform is not triggered by that. You need to trigger that as well.

If you always want to autoplay, you can add `controls.play();` to the bottom of the `loaded` function in controls.js

**Comment by inquietto** [comment]
Works perfect!! thanks so much!!
